import { LitElement, html, css, TemplateResult, PropertyValues, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { consume } from '@lit/context';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
import { StoreController } from '@nanostores/lit';
import { strainLibraryContext, storeContext } from '../context';
import {
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
  mdiBottleTonicPlus,
  mdiWater,
  mdiContentCut,
  mdiAlertCircle,
  mdiStar,
} from '@mdi/js';
import { PlantEntity, StrainEntry, PlantDisplayData, StageDisplay } from '../types';
import { PlantUtils } from '../utils/plant-utils';
import { DragDropController, DragDropHost } from '../controllers/drag-drop-controller';
// Global imports removed
import type { GrowspaceStore } from '../store/growspace-store';
import './plant/plant-stats';
import { plantCardStyles } from '../styles/plant-card.styles';
import { sharedStyles } from '../styles/shared.styles';

@customElement('growspace-plant-card')
export class GrowspacePlantCard extends LitElement implements DragDropHost {
  @property({ attribute: false }) accessor plant!: PlantEntity;
  @property({ type: Number }) accessor row!: number;
  @property({ type: Number }) accessor col!: number;

  @consume({ context: strainLibraryContext, subscribe: true })
  accessor strainLibrary: StrainEntry[] = [];

  @consume({ context: storeContext })
  private accessor store!: GrowspaceStore;

  // UI state via StoreController - direct subscription to atoms
  private _isEditModeController!: StoreController<boolean>;
  private _selectedPlantsController!: StoreController<Set<string>>;

  connectedCallback() {
    super.connectedCallback();
    if (!this._isEditModeController && this.store) {
      this._isEditModeController = new StoreController(this, this.store.ui.$isEditMode);
      this._selectedPlantsController = new StoreController(this, this.store.ui.$selectedPlants);
    }
  }

  // Getters to satisfy DragDropHost interface
  get isEditMode(): boolean {
    return this._isEditModeController?.value ?? false;
  }

  get selected(): boolean {
    const plantId = this.plant?.attributes?.plant_id;
    return (plantId && this._selectedPlantsController?.value?.has(plantId)) || false;
  }

  // Instantiate controller
  private dragController = new DragDropController(this);

  // Computed display data
  get displayData(): PlantDisplayData | null {
    if (!this.plant) return null;
    return PlantUtils.getPlantDisplayData(this.plant, this.strainLibrary);
  }

  get _hasRecommendedPreset(): boolean {
    if (!this.plant || !this.store) return false;
    const growspaceId = this.plant.attributes.growspace_id;
    const device = this.store.data.$devices.get().find(d => d.device_id === growspaceId);
    if (!device || !device.nutrient_presets) return false;

    const currentStage = this.plant.attributes.stage;
    const daysInStage = (this.plant.attributes as any).days_in_stage || 0;

    return Object.values(device.nutrient_presets).some(p =>
      p.stage === currentStage && (!p.min_days_in_stage || daysInStage >= p.min_days_in_stage)
    );
  }

  // Placeholder for watering status, assuming it will be implemented elsewhere
  get _isRecentlyWatered(): boolean {
    // Example logic: check if last watered within the last 24 hours
    const lastWatered = this.plant.attributes.last_watered;
    if (!lastWatered) return false;
    const twentyFourHoursAgo = new Date();
    twentyFourHoursAgo.setHours(twentyFourHoursAgo.getHours() - 24);
    return new Date(lastWatered) > twentyFourHoursAgo;
  }


  static styles = [
    sharedStyles,
    plantCardStyles
  ];

  // --- Click Handlers ---

  public focus(options?: FocusOptions) {
    const card = this.shadowRoot?.querySelector('.plant-card-rich') as HTMLElement;
    if (card) {
      card.focus(options);
    } else {
      super.focus(options);
    }
  }

  private _handleClick() {
    this.dispatchEvent(
      new CustomEvent('plant-click', {
        detail: { plant: this.plant },
        bubbles: true,
        composed: true,
      })
    );
  }

  private _toggleSelection(e: Event) {
    e.stopPropagation();
    this.dispatchEvent(
      new CustomEvent('plant-toggle-selection', {
        detail: { plant: this.plant },
        bubbles: true,
        composed: true,
      })
    );
  }

  render() {
    const data = this.displayData;
    if (!this.plant || !data) return html``;

    const { stageColor, strainName, pheno, imageUrl, imageCropMeta, stages } = data;

    // Construct srcset for responsive images
    // If we have a WebP image, we assume a _small variant exists (generated by backend)
    let srcset = '';
    if (imageUrl && imageUrl.endsWith('.webp')) {
      const smallUrl = imageUrl.replace('.webp', '_small.webp');
      // Tell browser: use smallUrl if width <= 320px, otherwise imageUrl
      srcset = `${smallUrl} 320w, ${imageUrl} 1024w`;
    }

    return html`
      <div
        class="plant-card-rich"
        style=${styleMap({ '--stage-color': stageColor })}
        draggable="true"
        tabindex="0"
        @click=${this._handleClick}
      >
        ${imageUrl
        ? html`
              <img
                class="plant-card-bg"
                src="${imageUrl}"
                srcset="${srcset}"
                sizes="(max-width: 600px) 320px, 1024px"
                loading="lazy"
                decoding="async"
                alt="${strainName}"
                style="${PlantUtils.getImgStyle(imageCropMeta)}"
              />
              <div class="plant-card-overlay"></div>
            `
        : nothing}
        ${this.isEditMode
        ? html`
              <div
                class=${classMap({ 'plant-card-checkbox': true, 'selected': this.selected })}
                @click=${this._toggleSelection}
              >
                <svg
                  viewBox="0 0 24 24"
                  style=${styleMap({
          width: '24px',
          height: '24px',
          fill: this.selected ? 'var(--primary-color)' : 'rgba(255,255,255,0.7)'
        })}
                >
                  <path d="${this.selected ? mdiCheckboxMarked : mdiCheckboxBlankOutline}"></path>
                </svg>
              </div>
            `
        : nothing}
        <div class="status-icons">
            ${this.plant.attributes.last_training_technique ? html`
              <div class="status-icon training" title="Last trained with: ${this.plant.attributes.last_training_technique}">
                <ha-svg-icon .path=${mdiContentCut}></ha-svg-icon>
              </div>
            ` : nothing}

            ${this._isRecentlyWatered ? html`
              <div class="status-icon watering" title="Recently watered">
                <ha-svg-icon .path=${mdiWater}></ha-svg-icon>
              </div>
            ` : nothing}

            ${this.plant.attributes.problem ? html`
              <div class="status-icon problem" title="Problem detected: ${this.plant.attributes.problem}">
                <ha-svg-icon .path=${mdiAlertCircle}></ha-svg-icon>
              </div>
            ` : nothing}
          </div>
        <div class="plant-card-content">
          <div class="pc-info">
            <div class="pc-strain-name" title="${strainName}">${strainName}</div>
            ${pheno ? html`<div class="pc-pheno">${pheno}</div>` : nothing}
            <div style="display: flex; align-items: center; gap: 8px;">
               <div class="pc-stage">${this.plant.state || 'Unknown'}</div>
               ${this._hasRecommendedPreset ? html`
                 <ha-svg-icon
                    .path=${mdiStar}
                    style="--mdc-icon-size: 14px; color: var(--primary-color);" 
                    title="Nutrient Preset Recommended"
                 ></ha-svg-icon>
               ` : nothing}
            </div>
          </div>

          <growspace-plant-stats .stages=${stages}></growspace-plant-stats>
        </div>
      </div>
    `;
  }
}
