import { LitElement, html, css, TemplateResult, PropertyValues } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { consume } from '@lit/context';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
import { strainLibraryContext } from '../context';
import {
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
} from '@mdi/js';
import { PlantEntity, StrainEntry, PlantDisplayData, StageDisplay } from '../types';
import { PlantUtils } from '../utils/plant-utils';
import { DragDropController, DragDropHost } from '../controllers/drag-drop-controller';
import './plant/plant-stats';
import { plantCardStyles } from '../styles/plant-card.styles';
import { sharedStyles } from '../styles/shared.styles';

@customElement('growspace-plant-card')
export class GrowspacePlantCard extends LitElement implements DragDropHost {
  @property({ attribute: false }) accessor plant!: PlantEntity;
  @property({ type: Number }) accessor row!: number;
  @property({ type: Number }) accessor col!: number;

  @consume({ context: strainLibraryContext, subscribe: true })
  accessor strainLibrary: StrainEntry[] = [];

  @property({ type: Boolean }) accessor isEditMode = false;
  @property({ type: Boolean }) accessor selected = false;

  // Instantiate controller
  private dragController = new DragDropController(this);

  // Computed display data
  get displayData(): PlantDisplayData | null {
    if (!this.plant) return null;
    return PlantUtils.getPlantDisplayData(this.plant, this.strainLibrary);
  }


  static styles = [
    sharedStyles,
    plantCardStyles
  ];

  // --- Click Handlers ---

  public focus(options?: FocusOptions) {
    const card = this.shadowRoot?.querySelector('.plant-card-rich') as HTMLElement;
    if (card) {
      card.focus(options);
    } else {
      super.focus(options);
    }
  }

  private _handleClick() {
    this.dispatchEvent(
      new CustomEvent('plant-click', {
        detail: { plant: this.plant },
        bubbles: true,
        composed: true,
      })
    );
  }

  private _toggleSelection(e: Event) {
    e.stopPropagation();
    this.dispatchEvent(
      new CustomEvent('plant-toggle-selection', {
        detail: { plant: this.plant },
        bubbles: true,
        composed: true,
      })
    );
  }

  render() {
    const data = this.displayData;
    if (!this.plant || !data) return html``;

    const { stageColor, strainName, pheno, imageUrl, imageCropMeta, stages } = data;

    // Construct srcset for responsive images
    // If we have a WebP image, we assume a _small variant exists (generated by backend)
    let srcset = '';
    if (imageUrl && imageUrl.endsWith('.webp')) {
      const smallUrl = imageUrl.replace('.webp', '_small.webp');
      // Tell browser: use smallUrl if width <= 320px, otherwise imageUrl
      srcset = `${smallUrl} 320w, ${imageUrl} 1024w`;
    }

    return html`
      <div
        class="plant-card-rich"
        style=${styleMap({ '--stage-color': stageColor })}
        draggable="true"
        tabindex="0"
        @click=${this._handleClick}
      >
        ${imageUrl
        ? html`
              <img
                class="plant-card-bg"
                src="${imageUrl}"
                srcset="${srcset}"
                sizes="(max-width: 600px) 320px, 1024px"
                loading="lazy"
                decoding="async"
                alt="${strainName}"
                style="${PlantUtils.getImgStyle(imageCropMeta)}"
              />
              <div class="plant-card-overlay"></div>
            `
        : ''}
        ${this.isEditMode
        ? html`
              <div
                class=${classMap({ 'plant-card-checkbox': true, 'selected': this.selected })}
                @click=${this._toggleSelection}
              >
                <svg
                  viewBox="0 0 24 24"
                  style=${styleMap({
          width: '24px',
          height: '24px',
          fill: this.selected ? 'var(--primary-color)' : 'rgba(255,255,255,0.7)'
        })}
                >
                  <path d="${this.selected ? mdiCheckboxMarked : mdiCheckboxBlankOutline}"></path>
                </svg>
              </div>
            `
        : ''}

        <div class="plant-card-content">
          <div class="pc-info">
            <div class="pc-strain-name" title="${strainName}">${strainName}</div>
            ${pheno ? html`<div class="pc-pheno">${pheno}</div>` : ''}
            <div class="pc-stage">${this.plant.state || 'Unknown'}</div>
          </div>

          <growspace-plant-stats .stages=${stages}></growspace-plant-stats>
        </div>
      </div>
    `;
  }
}
